import { c2paCheck } from "./checkers/c2pa.js"

class Config {
  constructor(ignore, openai_api_key) {
    this.ignore = ignore
    this.openai_api_key = openai_api_key
  }
}

// Image analysis

// Class ImageAnalysisResult : the thing that is returned when executing imageAnalysis
export class ImageAnalysisResult {
  constructor(c2pa) {
    this.c2pa = c2pa
  }

  get getFlaggedList() {
    const result = []
    if (this.c2pa.flagged == true) { result.push("c2pa") }

    return result
  }

  get getFlaggedCount() {
    const result = 0
    if (this.c2pa.flagged == true) { result++ }
  }

  // Check if an analysis flagged the content. If the content is not flagged by any detector, return false. Else, return true.
  get isFlagged() {
    if (this.c2pa.flagged == true) {
      return true
    } else {
      return false
    }
  }

  // Get the "authors" of the tile. The autor is the company behind the content generation. For example, an image generated by ChatGPT should be flagged as made by OpenAI
  get authorsList() {
    const result = []
    if (this.c2pa.flagged == true) {
      result.push(this.c2pa.manifest.signature_info.issuer)
    }
    return result
  }
}

// The function to execute to analyse an image.
// File is a Blob.
export async function imageAnalysis(file) {
  const c2pa = await c2paCheck(file)
  return new ImageAnalysisResult(c2pa)
}


// Video analysis

// Class VideoAnalysisResult : the thing that is returned when executing videoAnalysis
export class VideoAnalysisResult {
  constructor(c2pa) {
    this.c2pa = c2pa
  }

  get getFlaggedList() {
    const result = []
    if (this.c2pa.flagged == true) { result.push("c2pa") }

    return result
  }

  get getFlaggedCount() {
    const result = 0
    if (this.c2pa.flagged == true) { result++ }
  }

// Check if an analysis flagged the content. If the content is not flagged by any detector, return false. Else, return true.
  get isFlagged() {
    if (this.c2pa.flagged == true) {
      return true
    } else {
      return false
    }
  }

  // Get the "authors" of the tile. The autor is the company behind the content generation. For example, a video generated by Sora should be flagged as made by OpenAI
  get authorsList() {
    const result = []
    if (this.c2pa.flagged == true) {
      result.push(this.c2pa.manifest.signature_info.issuer)
    }
    return result
  }
}

// The function to execute to analyse an video.
// File is a Blob.
export async function videoAnalysis(file) {
  const c2pa = await c2paCheck(file)
  return new VideoAnalysisResult(c2pa)
}
