import { c2paCheck } from "./checkers/c2pa.js"
import { openaiAnalysis } from "./checkers/openai.js"

export class Config {
  constructor(ignore, openai_api_key) {
    this.ignore = ignore
    this.openai_api_key = openai_api_key
  }
}

// Image analysis

// Class ImageAnalysisResult : the thing that is returned when executing imageAnalysis
export class ImageAnalysisResult {
  constructor(c2pa, openai) {
    this.c2pa = c2pa
    this.openai = openai
  }

  get getFlaggedList() {
    const result = []
    if (this.c2pa?.flagged) { result.push("c2pa") }
    if (this.openai?.flagged) { result.push("openai") }

    return result
  }

  get getFlaggedCount() {
    const result = 0
    if (this.c2pa?.flagged) { result++ }
    if (this.openai?.flagged) { result++ }
  }

  // Check if an analysis flagged the content. If the content is not flagged by any detector, return false. Else, return true.
  get isFlagged() {
    if (this.c2pa?.flagged || this.openai?.flagged) {
      return true
    } else {
      return false
    }
  }

  // Get the "authors" of the tile. The autor is the company behind the content generation. For example, an image generated by ChatGPT should be flagged as made by OpenAI
  get authorsList() {
    const result = []

    if (this.c2pa?.flagged) { result.push(this.c2pa.manifest.signature_info.issuer) }
    if (this.openai?.flagged) { result.push("OpenAI") }

    return result
  }
}

var defaultConfig = new Config([], null)

// The function to execute to analyse an image.
// File is a Blob.
export async function imageAnalysis(file, config = defaultConfig) {
  let c2pa
  let openai

  if (!config.ignore.includes("c2pa")) {
    c2pa = await c2paCheck(file)
  }

  if (config.openai_api_key != null && !config.ignore.includes("openai")) {
    openai = await openaiAnalysis(file, config.openai_api_key)
  }

  return new ImageAnalysisResult(c2pa, openai)
}


// Video analysis

// Class VideoAnalysisResult : the thing that is returned when executing videoAnalysis
export class VideoAnalysisResult {
  constructor(c2pa) {
    this.c2pa = c2pa
  }

  get getFlaggedList() {
    const result = []
    if (this.c2pa.flagged == true) { result.push("c2pa") }

    return result
  }

  get getFlaggedCount() {
    const result = 0
    if (this.c2pa.flagged == true) { result++ }
  }

// Check if an analysis flagged the content. If the content is not flagged by any detector, return false. Else, return true.
  get isFlagged() {
    if (this.c2pa.flagged == true) {
      return true
    } else {
      return false
    }
  }

  // Get the "authors" of the tile. The autor is the company behind the content generation. For example, a video generated by Sora should be flagged as made by OpenAI
  get authorsList() {
    const result = []
    if (this.c2pa.flagged == true) {
      result.push(this.c2pa.manifest.signature_info.issuer)
    }
    return result
  }
}

// The function to execute to analyse an video.
// File is a Blob.
export async function videoAnalysis(file) {
  const c2pa = await c2paCheck(file)
  return new VideoAnalysisResult(c2pa)
}
